services:
  web:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./src:/data/www
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80